name: Currency Monitor

on:
  schedule:
    - cron: '*/30 * * * *'
    workflow_dispatch:

permissions:
  contents: write

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Monitor Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: Commit and Push if changed
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          
          # Check if there are changes in last_run.json
          if [[ -n $(git status --porcelain last_run.json) ]]; then
            echo "Changes detected in last_run.json. Committing..."
            git add last_run.json
            git commit -m "Update exchange rate history [skip ci]"
            git push
          else
            echo "No changes in last_run.json. Skipping commit."
          fi
